import { Geist, Geist_Mono } from "next/font/google";
import Header from "./components/Header";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/lib/auth";
import UserSessionSync from "./components/UserSessionSync";
import Providers from "@/lib/provider";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth(); // fetches server-side session
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider session={session}>
          <Providers>
            <UserSessionSync />
            <Header />
            {children}
            <Toaster></Toaster>
          </Providers>
        </SessionProvider>
      </body>
    </html>
  );
}
